//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaDeDateContainer : DbContext
    {
        public BazaDeDateContainer()
            : base("name=BazaDeDateContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Incasari> Incasari { get; set; }
        public virtual DbSet<CategVenit> CategVenit { get; set; }
        public virtual DbSet<LocalizareVenit> LocalizareVenit { get; set; }
        public virtual DbSet<Plati> Plati { get; set; }
        public virtual DbSet<CategChelt> CategChelt { get; set; }
    }
}
