//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategVenit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategVenit()
        {
            this.Incasaris = new HashSet<Incasari>();
        }
    
        public int IdCategVenit { get; set; }
        public string DescriereVenit { get; set; }
        public int LocalizareVenitIdLocalizareVenit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incasari> Incasaris { get; set; }
        public virtual LocalizareVenit LocalizareVenit { get; set; }
    }
}
