//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plati
    {
        public int IdPlata { get; set; }
        public string Descriere { get; set; }
        public string Suma { get; set; }
        public string DataT { get; set; }
        public int LocalizareVenitIdLocalizareVenit { get; set; }
        public int CategCheltIdCategChelt { get; set; }
    
        public virtual LocalizareVenit LocalizareVenit { get; set; }
        public virtual CategChelt CategChelt { get; set; }
    }
}
